export const tableHeader = [
  "Sl",
  "Employee Name",
  "Type",
  "Apply Date",
  "Leave Start Date",
  "Leave End Date",
  "Days",
  "Reason",
  "Approved Date",
  "Approved Start Date",
  "Approved End Date",
  "Approved Days",
  "Manager Comments",
  "Status",
  "Action",
];
