import { tagTypes } from "../tagTypes";
import { baseApi } from "./baseApi";

export const userApi = baseApi.injectEndpoints({
  endpoints: (build) => ({
    getAllPayment: build.query({
      query: () => ({
        url: "/payment",
        method: "GET",
      }),
      providesTags: [tagTypes.admin],
    }),
  }), // Properly closed the endpoints object
});

// Exporting hooks generated by RTK Query
export const { useGetAllPaymentQuery } = userApi;
