export const fakeData = [
  {
    id: 1,
    name: "Rakib Hosen",
    basicSalary: 0,
    totalBenefit: 1240,
    transportAllowance: 0,
    grossSalary: 1290,
    stateIncomeTax: 0,
    socialSecurityNpf: 0,
    employerContribution: 0,
    loanDeduction: 450,
    salaryAdvance: 0,
    totalDeductions: 14890,
    netSalary: 15800,
  },
  {
    id: 2,
    name: "Rakib Hosen",
    basicSalary: 0,
    totalBenefit: 1240,
    transportAllowance: 0,
    grossSalary: 1290,
    stateIncomeTax: 0,
    socialSecurityNpf: 0,
    employerContribution: 0,
    loanDeduction: 450,
    salaryAdvance: 0,
    totalDeductions: 14890,
    netSalary: 15800,
  },
  {
    id: 3,
    name: "Rakib Hosen",
    basicSalary: 0,
    totalBenefit: 1240,
    transportAllowance: 0,
    grossSalary: 1290,
    stateIncomeTax: 0,
    socialSecurityNpf: 0,
    employerContribution: 0,
    loanDeduction: 450,
    salaryAdvance: 0,
    totalDeductions: 14890,
    netSalary: 15800,
  },
  {
    id: 4,
    name: "Rakib Hosen",
    basicSalary: 0,
    totalBenefit: 1240,
    transportAllowance: 0,
    grossSalary: 1290,
    stateIncomeTax: 0,
    socialSecurityNpf: 0,
    employerContribution: 0,
    loanDeduction: 450,
    salaryAdvance: 0,
    totalDeductions: 14890,
    netSalary: 15800,
  },
  {
    id: 5,
    name: "Rakib Hosen",
    basicSalary: 0,
    totalBenefit: 1240,
    transportAllowance: 0,
    grossSalary: 1290,
    stateIncomeTax: 0,
    socialSecurityNpf: 0,
    employerContribution: 0,
    loanDeduction: 450,
    salaryAdvance: 0,
    totalDeductions: 14890,
    netSalary: 15800,
  },
];
