export const AllNoticeData = [
    {
      id: 1,
      noticeType: "sfsfsf",
      description: "dsffdsf",
      noticeDate: "2024-10-22",
      noticeBy: "sdfdfsf",
    },
    {
      id: 2,
      noticeType: "Testing",
      description: "Testing",
      noticeDate: "2024-10-23",
      noticeBy: "Boss",
    },
    {
      id: 3,
      noticeType: "sample",
      description: "sample",
      noticeDate: "2024-10-13",
      noticeBy: "Y",
    },
    {
      id: 4,
      noticeType: "Meeting",
      description: "Get ready for meeting at 6",
      noticeDate: "2024-08-22",
      noticeBy: "Siddique Abdullah",
    },
    {
      id: 5,
      noticeType: "Immediate management meeting",
      description: "management decision",
      noticeDate: "2024-07-11",
      noticeBy: "Mr Michael",
    },
    {
      id: 6,
      noticeType: "Meeting",
      description: "our organization will organize an annual report",
      noticeDate: "2024-07-10",
      noticeBy: "Maisha Lucy Zamora Gonzales",
    },
    {
      id: 7,
      noticeType: "Admin Notice",
      description: "Admin Notice",
      noticeDate: "2024-06-05",
      noticeBy: "from management decision",
    },
    {
      id: 8,
      noticeType: "Reply 'stop' at any time to opt out",
      description: "Facilis mollit harum",
      noticeDate: "2026-11-01",
      noticeBy: "Occaecat tempore of",
    },
    {
      id: 9,
      noticeType: "Sed itaque officiis",
      description: "Fuga In eaque disti",
      noticeDate: "2024-08-28",
      noticeBy: "Voluptate culpa labo",
    },
    {
      id: 10,
      noticeType: "Holiday Notice",
      description: "Office will remain closed for maintenance",
      noticeDate: "2024-12-01",
      noticeBy: "Admin Team",
    },
    {
      id: 11,
      noticeType: "Team Building Event",
      description: "Join us for a fun-filled event",
      noticeDate: "2024-12-10",
      noticeBy: "HR Department",
    },
    {
      id: 12,
      noticeType: "System Downtime",
      description: "Scheduled system maintenance on Sunday",
      noticeDate: "2024-11-30",
      noticeBy: "IT Team",
    },
    {
      id: 13,
      noticeType: "Security Update",
      description: "Ensure to update your passwords",
      noticeDate: "2024-11-20",
      noticeBy: "Security Team",
    },
    {
      id: 14,
      noticeType: "Employee Feedback",
      description: "Submit your feedback by the end of the month",
      noticeDate: "2024-11-25",
      noticeBy: "Management",
    },
    {
      id: 15,
      noticeType: "Performance Review",
      description: "Annual performance review starts next week",
      noticeDate: "2024-12-05",
      noticeBy: "HR Manager",
    },
  ];
  
  export const noticeModalInputFiled= [
    {
      name: "noticeType",
      label: "Notice type",
      type: "text",
      placeholder: "Notice type",
      required: true,
    },
    {
      name: "description",
      label: "Notice description",
      type: "text",
      placeholder: "Notice description",
      required: true,
    },
    {
      name: "noticeDate",
      label: "Notice date",
      type: "date",
      placeholder: "Notice date",
      required: true,
    },
  //   {
  //     name: "noticeAttachment",
  //     label: "Notice attachment",
  //     type: "file",
  //     placeholder: "Choose File",
  //     required: true,
  //   },
    {
      name: "noticeBy",
      label: "Notice by",
      type: "text",
      placeholder: "Notice by",
      required: true,
    },
  ];