export const fakeData = [
  {
    id: 1,
    salaryName: "January Salary",
    generateDate: "2024-01-01",
    generateBy: "Admin",
    status: "Approved",
    approvedDate: "2024-01-01",
    approvedBy: "Admin",
  },
  {
    id: 2,
    salaryName: "February Salary",
    generateDate: "2024-02-01",
    generateBy: "Admin",
    status: "Approved",
    approvedDate: "2024-02-05",
    approvedBy: "Admin",
  },
  {
    id: 3,
    salaryName: "March Salary",
    generateDate: "2024-03-01",
    generateBy: "Admin",
    status: "Approved",
    approvedDate: "2024-03-03",
    approvedBy: "Admin",
  },
  {
    id: 4,
    salaryName: "April Salary",
    generateDate: "2024-04-01",
    generateBy: "Admin",
    status: "Approved",
    approvedDate: "2024-04-01",
    approvedBy: "Admin",
  },
  {
    id: 5,
    salaryName: "May Salary",
    generateDate: "2024-05-01",
    generateBy: "Admin",
    status: "Approved",
    approvedDate: "2024-05-10",
    approvedBy: "Admin",
  },
];
