export const fakeData = [
  {
    Sl: 1,
    EmployeeId: "000028",
    NameOfEmployee: "Mohmed Afifi Akram",
    Email: "mohaafiif@gmail.com",
    Mobileno: "26523333",
    Dateofbirth: "",
    Designation: "Account Executive",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 2,
    EmployeeId: "000027",
    NameOfEmployee: "Uma Stafford",
    Email: "nocunocu@mailinator.com",
    Mobileno: "+1(617) 434-2319",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 3,
    EmployeeId: "000026",
    NameOfEmployee: "Khubab Ahmed",
    Email: "khubab@gmail.com",
    Mobileno: "0300-1234567",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 4,
    EmployeeId: "000025",
    NameOfEmployee: "Iman",
    Email: "fdsafdas@gmail.com",
    Mobileno: "09876",
    Dateofbirth: "",
    Designation: "Data Analysis",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 5,
    EmployeeId: "000024",
    NameOfEmployee: "Thomas Goodman",
    Email: "gapanalos@mailinator.com",
    Mobileno: "+1(261) 424-8691",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 6,
    EmployeeId: "000023",
    NameOfEmployee: "Jaquelyn White",
    Email: "leqyma@mailinator.com",
    Mobileno: "+1(195) 686-1843",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 7,
    EmployeeId: "000022",
    NameOfEmployee: "Dawn Cobb",
    Email: "mecy@mailinator.com",
    Mobileno: "+1(104) 683-6454",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 8,
    EmployeeId: "000021",
    NameOfEmployee: "Odysseus Glover",
    Email: "bipem@mailinator.com",
    Mobileno: "+1(724) 777-1716",
    Dateofbirth: "",
    Designation: "",
    Joiningdate: "",
    Status: "Active",
  },
  {
    Sl: 9,
    EmployeeId: "000020",
    NameOfEmployee: "Oleg Hall Larson Sloan",
    Email: "zyhok@mailinator.com",
    Mobileno: "+1(747) 106-4191",
    Dateofbirth: "2015-06-06",
    Designation: "",
    Joiningdate: "1998-01-13",
    Status: "Active",
  },
  {
    Sl: 10,
    EmployeeId: "000019",
    NameOfEmployee: "Abra Nelle Barron Hyde",
    Email: "wocynyh@mailinator.com",
    Mobileno: "+1(126) 306-1032",
    Dateofbirth: "2012-02-01",
    Designation: "",
    Joiningdate: "1973-05-06",
    Status: "Active",
  },
];
