export interface Employee {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  email: string;
  password: string;
  phoneNumber: string;
  country: string;
  passport: string;
  nidNumber: string;
  alternateNumber?: string;
  city: string;
  attendanceShift: string;
  address: string;
  designation: string;
  dateOfBirth: string;
  joiningDate: string;
  accountNumber: string;
  tinNumber: string;
  branchAddress: string;
  routingNumber: string;
  basicSalary: number;
  transportAllowance: number;
  grossSalary: number;
  medicalBenefit: number;
  transportationBenefit: number;
  familyBenefit: number;
  otherBenefit: number;
  departmentId: string;
  subDepartmentId?: string;
  position: string;
  dutyType: string;
  hireDate: string; // ISO 8601 date string
  rehireDate?: string | null;
  terminationDate?: string | null;
  cardNumber: string;
  monthlyWorkHours: number;
  workPermit: boolean;
  payFrequency: string;
  payFrequencyText: string;
  hourlyRate: number;
  hourlyRate2?: number | null;
  employeeGrade: string;
  terminationReason?: string | null;
  workInCity: string;
  employeeType: string;
  gender: string;
  maritalStatus: string;
  numberOfKids: number;
  sosNumber: string;
  religion: string;
  ethnicGroup: string;
  profileImage: string;
  passportPhoto: string;
  emergencyContactPerson: string;
  emergencyContactRelationship: string;
  emergencyContactNumber: string;
  emergencyHomePhone?: string;
  emergencyWorkPhone?: string | null;
  alternateEmergencyContact?: string;
  alternateEmergencyHomePhone?: string;
  alternateEmergencyWorkPhone?: string | null;
  bloodGroup: string;
  healthCondition: string;
  isDisabled: boolean;
  disabilitiesDescription?: string | null;
  homeEmail: string;
  homePhone: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}
