export const biologicalInfos = [
  {
    name: "dateOfBirth",
    placeholder: "Date of Birth",
    type: "date",
    label: "Date of Birth",
    isSelect: false,
    required: true,
  },
  {
    name: "gander",
    placeholder: "Gender",
    type: "text",
    label: "Gender",
    isSelect: false,
    required: true,
  },
  {
    name: "maritalStatus",
    placeholder: "Marital Status",
    type: "text",
    label: "Marital Status",
    isSelect: false,
    required: false,
  },
  {
    name: "noOfKids",
    placeholder: "Number of Kids",
    type: "text",
    label: "Number of Kids",
    isSelect: false,
    required: false,
  },
  {
    name: "sos",
    placeholder: "SOS",
    type: "text",
    label: "SOS",
    isSelect: false,
    required: true,
  },
  {
    name: "religion",
    placeholder: "Religion",
    type: "text",
    label: "Religion",
    isSelect: false,
    required: false,
  },
  {
    name: "ethnicGroup",
    placeholder: "Ethnic Group",
    type: "text",
    label: "Ethnic Group",
    isSelect: false,
    required: false,
  },
  {
    name: "profileImage",
    placeholder: "Profile Image",
    type: "file",
    label: "Profile Image",
    isSelect: false,
    required: false,
  },
  {
    name: "emergencyContactPerson",
    placeholder: "Emergency Contact Person",
    type: "text",
    label: "Emergency Contact Person",
    isSelect: false,
    required: true,
  },
  {
    name: "emergencyContactRelationship",
    placeholder: "Emergency Contact Relationship",
    type: "text",
    label: "Emergency Contact Relationship",
    isSelect: false,
    required: false,
  },
  {
    name: "emergencyContact",
    placeholder: "Emergency Contact",
    type: "text",
    label: "Emergency Contact",
    isSelect: false,
    required: true,
  },
  {
    name: "emergencyHomePhone",
    placeholder: "Emergency Home Phone",
    type: "text",
    label: "Emergency Home Phone",
    isSelect: false,
    required: false,
  },
  {
    name: "emergencyWorkPhone",
    placeholder: "Emergency Work Phone",
    type: "text",
    label: "Emergency Work Phone",
    isSelect: false,
    required: false,
  },
  {
    name: "alterEmergencyContact",
    placeholder: "Alternate Emergency Contact",
    type: "text",
    label: "Alternate Emergency Contact",
    isSelect: false,
    required: false,
  },
  {
    name: "alterEmergencyHomePhone",
    placeholder: "Alternate Emergency Home Phone",
    type: "text",
    label: "Alternate Emergency Home Phone",
    isSelect: false,
    required: false,
  },
  {
    name: "alterEmergencyWorkPhone",
    placeholder: "Alternate Emergency Work Phone",
    type: "text",
    label: "Alternate Emergency Work Phone",
    isSelect: false,
    required: false,
  },
];
