const country = [
  { key: "Bangladesh", value: "Bangladesh" },
  { key: "United States", value: "United States" },
  { key: "India", value: "India" },
  { key: "United Kingdom", value: "United Kingdom" },
  { key: "Canada", value: "Canada" },
  { key: "Australia", value: "Australia" },
  { key: "Germany", value: "Germany" },
  { key: "France", value: "France" },
  { key: "Italy", value: "Italy" },
  { key: "Japan", value: "Japan" },
  { key: "China", value: "China" },
  { key: "Russia", value: "Russia" },
  { key: "Brazil", value: "Brazil" },
  { key: "Mexico", value: "Mexico" },
  { key: "Spain", value: "Spain" },
  { key: "South Korea", value: "South Korea" },
  { key: "Saudi Arabia", value: "Saudi Arabia" },
  { key: "Argentina", value: "Argentina" },
  { key: "South Africa", value: "South Africa" },
  { key: "Egypt", value: "Egypt" },
  { key: "Nigeria", value: "Nigeria" },
  { key: "Pakistan", value: "Pakistan" },
  { key: "Vietnam", value: "Vietnam" },
  { key: "Turkey", value: "Turkey" },
  { key: "Thailand", value: "Thailand" },
  { key: "Indonesia", value: "Indonesia" },
  { key: "Ukraine", value: "Ukraine" },
  { key: "Poland", value: "Poland" },
  { key: "Netherlands", value: "Netherlands" },
  { key: "Belgium", value: "Belgium" },
  { key: "Switzerland", value: "Switzerland" },
  { key: "Sweden", value: "Sweden" },
  { key: "Norway", value: "Norway" },
  { key: "Denmark", value: "Denmark" },
  { key: "Finland", value: "Finland" },
  { key: "Greece", value: "Greece" },
  { key: "Portugal", value: "Portugal" },
  { key: "Czech Republic", value: "Czech Republic" },
  { key: "Hungary", value: "Hungary" },
  { key: "Romania", value: "Romania" },
  { key: "Israel", value: "Israel" },
  { key: "Malaysia", value: "Malaysia" },
  { key: "Singapore", value: "Singapore" },
  { key: "Philippines", value: "Philippines" },
  { key: "New Zealand", value: "New Zealand" },
  { key: "Chile", value: "Chile" },
  { key: "Colombia", value: "Colombia" },
  { key: "Peru", value: "Peru" },
  { key: "Kenya", value: "Kenya" },
  { key: "Morocco", value: "Morocco" },
  { key: "Iraq", value: "Iraq" },
  { key: "Kuwait", value: "Kuwait" },
  { key: "Qatar", value: "Qatar" },
];

const attendanceTime = [
  { key: "Normal Shift", value: "Normal Shift" },
  { key: "Generale Shift", value: "Generale Shift" },
  { key: "Test", value: "Test" },
  { key: "Regular Working days ", value: "Regular Working daysTest" },
];

export const basicInfos = [
  {
    name: "firstName",
    placeholder: "First Name",
    type: "text",
    label: "First Name",
    isSelect: false,
    required: true,
  },
  {
    name: "middleName",
    placeholder: "Middle Name",
    type: "text",
    label: "Middle Name",
    isSelect: false,
    required: false,
  },
  {
    name: "lastName",
    placeholder: "Last Name",
    type: "text",
    label: "Last Name",
    isSelect: false,
    required: true,
  },
  {
    name: "email",
    placeholder: "Email",
    type: "email",
    label: "Email",
    isSelect: false,
    required: true,
  },
  {
    name: "phone",
    placeholder: "Phone",
    type: "number",
    label: "Phone",
    isSelect: false,
    required: true,
  },
  {
    name: "country",
    label: "Country",
    isSelect: true,
    options: country,
    placeholder: "Select Country",
    required: false,
  },
  {
    name: "city",
    placeholder: "City",
    type: "text",
    label: "City",
    isSelect: false,
    required: false,
  },
  {
    name: "zip",
    placeholder: "Zip",
    type: "text",
    required: false,
    label: "Zip",
    isSelect: false,
  },
  {
    name: "alternatePhone",
    placeholder: "Alternate Phone",
    type: "text",
    required: false,
    label: "Alternate Phone",
    isSelect: false,
  },
  {
    name: "nationalIdNo",
    placeholder: "National id no",
    type: "text",
    label: "National id no",
    isSelect: false,
    required: false,
  },
  {
    name: "iqamaNo",
    placeholder: "Iqama no",
    type: "text",
    label: "Iqama no",
    isSelect: false,
    required: false,
  },
  {
    name: "passportNo",
    placeholder: "Passport No",
    type: "text",
    label: "Passport No",
    isSelect: false,
    required: false,
  },
  {
    name: "drivingLicenseNo",
    placeholder: "Driving license no",
    type: "text",
    label: "Driving license no",
    isSelect: false,
    required: false,
  },
  {
    name: "attendanceTime",
    label: "Attendance time",
    isSelect: true,
    options: attendanceTime,
    placeholder: "Select attendance time",
    required: false,
  },
];

export const basicInfoState = {
  firstName: "",
  middleName: "",
  lastName: "",
  email: "",
  phone: "",
  country: "",
  city: "",
  zip: "",
  alternatePhone: "",
  nationalIdNo: "",
  iqamaNo: "",
  passportNo: "",
  drivingLicenseNo: "",
  attendanceTime: "",
};

export const salaryAndBankInfo = {
  accountNumber: "",
  branchAddress: "",
  bankName: "",
  bbanNum: "",
  tinNo: "",
  basicSalary: "",
  grossSalary: "",
  transportAllowance: "",
  medicalBenefit: "",
  familyBenefit: "",
  transportationBenefit: "",
  otherBenefit: "",
};

export const personalInformation = {
  department: "",
  payFrequency: "",
  subDepartment: "",
  payFrequencyText: "",
  position: "",
  hourlyRate: "",
  dutyType: "",
  hourlyRate2: "",
  joiningDate: "",
  employeeGrade: "",
  hireDate: "",
  terminationReason: "",
  rehireDate: "",
  workInCity: "",
  terminationDate: "",
  employeeType: "",
  cardNo: "",
  voluntaryTermination: "",
  monthlyWorkHours: "",
  workPermit: "",
};

export const biologicalInfoContact = {
  dateOfBirth: "",
  gander: "",
  maritalStatus: "",
  noOfKids: "",
  sos: "",
  religion: "",
  ethnicGroup: "",
  profileImage: "",
  emergencyContactPerson: "",
  emergencyContactRelationship: "",
  emergencyContact: "",
  emergencyHomePhone: "",
  emergencyWorkPhone: "",
  alterEmergencyContact: "",
  alterEmergencyHomePhone: "",
  alterEmergencyWorkPhone: "",
};

export const others = {
  bloodGroup: "",
  healthCondition: "",
  isDisable: false,
  disabilitiesDesc: "",
  homeEmail: "",
  homePhone: "",
  cellPhone: "",
  docTitle: "",
  file: "",
  expiryDate: "",
};

export const supervisor = {
  isSupervisor: false,
  email: "",
  password: "",
};
