import {
  TBasicInfoState,
  TBiologicalInfoContact,
  TOthers,
  TPersonalInformation,
  TSalaryAndBankInfo,
  TSupervisor,
} from "@/app/types";

const country = [
  { key: "Bangladesh", value: "Bangladesh" },
  { key: "United States", value: "United States" },
  { key: "India", value: "India" },
  { key: "United Kingdom", value: "United Kingdom" },
  { key: "Canada", value: "Canada" },
  { key: "Australia", value: "Australia" },
  { key: "Germany", value: "Germany" },
  { key: "France", value: "France" },
  { key: "Italy", value: "Italy" },
  { key: "Japan", value: "Japan" },
  { key: "China", value: "China" },
  { key: "Russia", value: "Russia" },
  { key: "Brazil", value: "Brazil" },
  { key: "Mexico", value: "Mexico" },
  { key: "Spain", value: "Spain" },
  { key: "South Korea", value: "South Korea" },
  { key: "Saudi Arabia", value: "Saudi Arabia" },
  { key: "Argentina", value: "Argentina" },
  { key: "South Africa", value: "South Africa" },
  { key: "Egypt", value: "Egypt" },
  { key: "Nigeria", value: "Nigeria" },
  { key: "Pakistan", value: "Pakistan" },
  { key: "Vietnam", value: "Vietnam" },
  { key: "Turkey", value: "Turkey" },
  { key: "Thailand", value: "Thailand" },
  { key: "Indonesia", value: "Indonesia" },
  { key: "Ukraine", value: "Ukraine" },
  { key: "Poland", value: "Poland" },
  { key: "Netherlands", value: "Netherlands" },
  { key: "Belgium", value: "Belgium" },
  { key: "Switzerland", value: "Switzerland" },
  { key: "Sweden", value: "Sweden" },
  { key: "Norway", value: "Norway" },
  { key: "Denmark", value: "Denmark" },
  { key: "Finland", value: "Finland" },
  { key: "Greece", value: "Greece" },
  { key: "Portugal", value: "Portugal" },
  { key: "Czech Republic", value: "Czech Republic" },
  { key: "Hungary", value: "Hungary" },
  { key: "Romania", value: "Romania" },
  { key: "Israel", value: "Israel" },
  { key: "Malaysia", value: "Malaysia" },
  { key: "Singapore", value: "Singapore" },
  { key: "Philippines", value: "Philippines" },
  { key: "New Zealand", value: "New Zealand" },
  { key: "Chile", value: "Chile" },
  { key: "Colombia", value: "Colombia" },
  { key: "Peru", value: "Peru" },
  { key: "Kenya", value: "Kenya" },
  { key: "Morocco", value: "Morocco" },
  { key: "Iraq", value: "Iraq" },
  { key: "Kuwait", value: "Kuwait" },
  { key: "Qatar", value: "Qatar" },
];

const attendanceTime = [
  { key: "GENERAL", value: "GENERAL" },
  { key: "OVERTIME", value: "OVERTIME" },
  { key: "NIGHT", value: "NIGHT" },
];

export const basicInfos = [
  {
    name: "firstName",
    placeholder: "First Name",
    type: "text",
    label: "First Name",
    isSelect: false,
    required: true,
  },
  {
    name: "middleName",
    placeholder: "Middle Name",
    type: "text",
    label: "Middle Name",
    isSelect: false,
    required: false,
  },
  {
    name: "lastName",
    placeholder: "Last Name",
    type: "text",
    label: "Last Name",
    isSelect: false,
    required: true,
  },
  {
    name: "phoneNumber",
    placeholder: "Phone",
    type: "number",
    label: "Phone",
    isSelect: false,
    required: true,
  },
  {
    name: "email",
    placeholder: "Email address",
    type: "email",
    label: "Email",
    isSelect: false,
    required: true,
  },
  {
    name: "password",
    placeholder: "Password",
    type: "password",
    label: "Password",
    isSelect: false,
    required: true,
  },
  {
    name: "country",
    label: "Country",
    isSelect: true,
    options: country,
    placeholder: "Select Country",
    required: false,
  },
  {
    name: "city",
    placeholder: "City",
    type: "text",
    label: "City",
    isSelect: false,
    required: false,
  },

  {
    name: "alternateNumber",
    placeholder: "Alternate Number",
    type: "text",
    required: false,
    label: "Alternate Number",
    isSelect: false,
  },
  {
    name: "nidNumber",
    placeholder: "National id no",
    type: "text",
    label: "National id no",
    isSelect: false,
    required: false,
  },

  {
    name: "passport",
    placeholder: "Passport No",
    type: "text",
    label: "Passport No",
    isSelect: false,
    required: false,
  },
  {
    name: "attendanceShift",
    label: "Attendance time",
    isSelect: true,
    options: attendanceTime,
    placeholder: "Select attendance time",
    required: false,
  },

  {
    name: "address",
    placeholder: "Address",
    type: "text",
    label: "Address",
    isSelect: false,
    required: false,
  },
  {
    name: "designation",
    placeholder: "Designation",
    type: "text",
    label: "Designation",
    isSelect: false,
    required: false,
  },
];

export const basicInfoState: TBasicInfoState = {
  firstName: "",
  middleName: "",
  lastName: "",
  email: "",
  password: "",
  phoneNumber: "",
  country: "",
  city: "",
  alternateNumber: "",
  nidNumber: "",
  passport: "",
  attendanceShift: "",
  address: "",
  designation: "",
};

export const salaryAndBankInfo: TSalaryAndBankInfo = {
  accountNumber: "",
  branchAddress: "",
  bankName: "",
  routingNumber: "",
  tinNumber: "",
  basicSalary: 0,
  grossSalary: 0,
  transportAllowance: 0,
  medicalBenefit: 0,
  familyBenefit: 0,
  transportationBenefit: 0,
  otherBenefit: 0,
};

export const personalInformation: TPersonalInformation = {
  departmentId: "",
  payFrequency: "",
  subDepartmentId: "",
  payFrequencyText: "",
  position: "",
  hourlyRate: "",
  dutyType: "",
  hourlyRate2: "",
  joiningDate: "",
  employeeGrade: "",
  hireDate: "",
  terminationReason: "",
  rehireDate: "",
  workInCity: "",
  terminationDate: "",
  employeeType: "",
  cardNumber: "",
  monthlyWorkHours: 0,
  workPermit: false,
};

export const biologicalInfoContact: TBiologicalInfoContact = {
  dateOfBirth: "",
  gender: "",
  maritalStatus: "",
  numberOfKids: 0,
  sosNumber: "",
  religion: "",
  ethnicGroup: "",
  profileImage: "",
  emergencyContactPerson: "",
  emergencyContactRelationship: "",
  emergencyContactNumber: "",
  emergencyHomePhone: "",
  emergencyWorkPhone: "",
  alternateEmergencyContact: "",
  alternateEmergencyHomePhone: "",
  alternateEmergencyWorkPhone: "",
};

export const others: TOthers = {
  bloodGroup: "",
  healthCondition: "",
  isDisabled: false,
  disabilitiesDesc: "",
  homeEmail: "",
  homePhone: "",
};

export const supervisor: TSupervisor = {
  isSupervisor: false,
  supervisorEmail: "",
  supervisorPassword: "",
};
