export const salaryAndBankInfos = [
  {
    name: "accountNumber",
    placeholder: "Account Number",
    type: "text",
    label: "Account Number",
    required: false,
  },
  {
    name: "branchAddress",
    placeholder: "Branch Address",
    type: "text",
    label: "Branch Address",
    required: false,
  },
  {
    name: "bankName",
    placeholder: "Bank Name",
    type: "text",
    label: "Bank Name",
    required: false,
  },
  {
    name: "routingNumber",
    placeholder: "Routing Number",
    type: "text",
    label: "Routing Number",
    required: false,
  },
  {
    name: "tinNumber",
    placeholder: "Tin No",
    type: "text",
    label: "Tin No",
    required: false,
  },
  {
    name: "basicSalary",
    placeholder: "Basic salary",
    type: "number",
    label: "Basic salary",
    required: true,
  },
  {
    name: "grossSalary",
    placeholder: "Gross Salary",
    type: "number",
    label: "Gross Salary",
    required: true,
  },
  {
    name: "transportAllowance",
    placeholder: "Transport Allowance",
    type: "number",
    label: "Transport Allowance",
    required: true,
  },
  {
    name: "medicalBenefit",
    placeholder: "Medical Benefit",
    type: "number",
    label: "Medical Benefit",
    required: false,
  },
  {
    name: "familyBenefit",
    placeholder: "Family Benefit",
    type: "number",
    label: "Family Benefit",
    required: false,
  },
  {
    name: "transportationBenefit",
    placeholder: "Transportation Benefit",
    type: "number",
    label: "Transportation Benefit",
    required: false,
  },
  {
    name: "otherBenefit",
    placeholder: "Other Benefit",
    type: "number",
    label: "Other Benefit",
    required: false,
  },
];
