export const loanFilterableFields = [
  "searchTerm",
  "id",
  "permittedBy",
  "loanNo",
  "amount",
  "interestRate",
  "installmentPeriod",
  "installmentCleared",
  "repaymentAmount",
  "approvedDate",
  "repaymentFrom",
  "subDepartment",
  "name",
];
export const loanSearchableFields = [
  "loanNo",
  "amount",
  "interestRate",
  "installmentPeriod",
  "installmentCleared",
  "repaymentAmount",
  "approvedDate",
  "repaymentFrom",
  "subDepartment",
  "name",
  "phoneNumber",
];
